version: "3.9"

services:
  omop54:
    build: .
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - CONSTRAINTS=true
      - OMOP_ON_FHIR=false
    volumes:
      - ./vocab:/VOCAB