version: "3.9"

services:
  omop54:
    build: .
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - CONSTRAINTS=false
      - OMOP_ON_FHIR=true
    volumes:
      - ./vocab:/VOCAB